name: Github actions
on: push
env:
  APP_IMAGE: keboola-component
  KBC_DEVELOPERPORTAL_APP: keboola.app-transformation-migrate
  KBC_DEVELOPERPORTAL_USERNAME: keboola+app_transformation_migrate_github_actions
  KBC_DEVELOPERPORTAL_VENDOR: keboola
  KBC_PROJECTID: 2703
  KBC_URL: https://connection.keboola.com/
  KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
  KBC_TOKEN: ${{ secrets.KBC_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image and run tests
        run: |
          docker build -t $APP_IMAGE .
          docker run
              -e KBC_TOKEN
              -e KBC_URL
              $APP_IMAGE
              composer ci
      - name: Push test image to ECR
        run: |
          docker pull quay.io/keboola/developer-portal-cli-v2:latest
          export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
          docker tag $APP_IMAGE:latest $REPOSITORY:test
          eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
          docker push $REPOSITORY:test
          docker pull quay.io/keboola/syrup-cli:latest
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/')
        run: ./deploy.sh
